### ISSUE TITLE
Implement Move AP & handle Tombstone better

### ISSUE THREAD

**Issue by melroy89** [MbinOrg/mbin#1126]
**Is your feature request related to a problem? Please describe.**

Would be nice to also support Move. So this allow people to move to another instance. Which is an important feature of ActivityPub protocol.

---

I also notice errors when we try to fetch Tombstone type of object. We might want to deal with this better.

**Describe the solution you'd like**

Implementing Moves & deal with Tombstone object types better.. 

**Additional context**

Mastodon Move docs: https://docs.joinmastodon.org/spec/activitypub/#Move

And the official w3c for Tombstone: https://www.w3.org/TR/activitypub/#delete-activity-outbox

Tombstone error message:

```sh
{"message":"cannot get the dependencies of the object, its type Tombstone is not one we can handle. {m]","context":{"t":"Tombstone","m":{"chain":[{"@context":["https://join-lemmy.org/context.json","https://www.w3.org/ns/activitystreams"],"id":"https://lemmy.world/comment/12307247","type":"Tombstone"}],"parent":null,"announce":null,"like":{"id":"https://lemmy.world/activities/like/a9f0e39d-4714-4644-b649-9b879135e906","actor":"https://lemmy.world/u/deania","@context":["https://join-lemmy.org/context.json","https://www.w3.org/ns/activitystreams"],"object":"https://lemmy.world/comment/12307247","type":"Like","audience":"https://midwest.social/c/lotrmemes"},"dislike":null}},"level":400,"level_name":"ERROR","channel":"app","datetime":"2024-09-12T21:58:13.037460+02:00","extra":{}}
```

**Comment by BentiGorlich** [comment]
Account migration features do not use tombstones: https://docs.joinmastodon.org/spec/activitypub/#Move

Tombstones are only used to indicate that something used to be there but got deleted, thats why the status code should be 410 gone when returning a tombstone. The error you added is from the ChainActivityHandler which does not interact with accounts, only content. When we get a tombstone in the ActivityPubHandler when fetching accounts we delete the account if we already have it.

However I of course agree that we should understand the `Move` activity and migrate followers over to the new account

**Comment by melroy89** [comment]
> Account migration features do not use tombstones: https://docs.joinmastodon.org/spec/activitypub/#Move
> 
> Tombstones are only used to indicate that something used to be there but got deleted, thats why the status code should be 410 gone when returning a tombstone. The error you added is from the ChainActivityHandler which does not interact with accounts, only content. When we get a tombstone in the ActivityPubHandler when fetching accounts we delete the account if we already have it.
> 
> However I of course agree that we should understand the `Move` activity and migrate followers over to the new account

I see, I updated the description & title. Hopefully this makes more sense now.

**Comment by melroy89** [comment]
See also: https://docs.joinmastodon.org/user/moving/#move

**Comment by melroy89** [comment]
Duplicate of: https://github.com/MbinOrg/mbin/issues/171
