### ISSUE TITLE
Search filters

### ISSUE THREAD

**Issue by Dark-Thoughts** [MbinOrg/mbin#1148]
**Is your feature request related to a problem? Please describe.**
When using the search function to look for specific search terms, it often is hard to find specifically threads of a given topic, as Mastodon posts seem to dominate a lot of the search results.

**Describe the solution you'd like**
Search filters to filter specifically for threads or microblogging posts could help bringing some order into the search results.

**Describe alternatives you've considered**
An UI alternative could be to have the search results display similar to the general feed in a context sensitive manner, where you can use the threads / microblogging / people / magazines elements in the top left to affect the search results. This could also consolidate the search field of the magazine page into the regular search bar.

**Comment by Dark-Thoughts** [comment]
Maybe related, definitely not a duplicate. I believe they're asking to search in specific places (magazines / user profiles).

**Comment by BentiGorlich** [comment]
This was actually already implement via #1167 and will land with 1.8.0
