### ISSUE TITLE
Strikethrough missing from federated Mastodon post

### ISSUE THREAD

**Issue by pbackus** [MbinOrg/mbin#1189]
**Describe the bug**

When a federated Mastodon post is viewed in Mbin, text that has a strikethrough on the original Mastodon instance is displayed without one on Mbin.

**On which Mbin instance did you find the bug?**

fedia.io

**Which Mbin version was running on the instance?**

1.7.2

**To Reproduce**

1. View a post with strikethrough on Mastodon (e.g., <https://pony.social/@luna/113250544308288695>)
2. View the same post on Mbin (e.g., <https://fedia.io/m/random/p/899560/I-m-curious-about-the-state-of-formatting-support-across-the>)

**Expected behavior**

The strikethrough should be displayed when viewing the post on Mbin.

**Screenshots**

Original Mastodon post:
![image](https://github.com/user-attachments/assets/2607c72e-52c9-404a-9632-9313232d4ef1)

Appearance on fedia.io:
![image](https://github.com/user-attachments/assets/9cd26bea-b2f6-4b1d-9c1b-260e29fc7468)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Browser Version: 130.0b8

**Comment by BentiGorlich** [comment]
The problem is probably in our html to markdown converter which seems to not support strikethroughs

**Comment by pbackus** [comment]
Relevant discussion here: <https://github.com/thephpleague/html-to-markdown/issues/185>
