### ISSUE TITLE
Local subscriber count in magazine info endpoint

### ISSUE THREAD

**Issue by ismailkarsli** [MbinOrg/mbin#1196]
**Is your feature request related to a problem? Please describe.**
I'm trying to add Mbin support to [Lemmy Federate](https://github.com/ismailkarsli/lemmy-federate) and the tool needs the local subscribers count in order to determine if it should sub/unsub.

**Describe the solution you'd like**
Add a local subscriber count field to the response of the `/api/magazine/name/{magazine_name}` endpoint.

**Comment by BentiGorlich** [comment]
@melroy89 I would just add property like `hasLocalSubscribers` instead of publishing the local subscriber counts which are also not available in the web UI.

What are you guys thinking about that?

**Comment by ismailkarsli** [comment]
@BentiGorlich Thanks for the change 🙏 I've added it too now.
