### ISSUE TITLE
Federated PMs not working

### ISSUE THREAD

**Issue by ismailkarsli** [MbinOrg/mbin#1197]
**Describe the bug**
Federated private messages between Lemmy and Mbin are not working.

**On which Mbin instance did you find the bug?**
- fedia.io > lemy.lol
- lemy.lol > fedia.io
- sh.itjust.works > fedia.io

**Which Mbin version was running on the instance?**
1.7.2

**To Reproduce**
just send a PM from Lemmy to Mbin and vice versa.

**Additional context**
Both Lemmy instances are using version 0.19.5.

**Comment by BentiGorlich** [comment]
It seems to be a fedia.io issue. Between infosec.pub and gehirneimer.de it works flawlessly


Am 21. Oktober 2024 14:51:34 MESZ schrieb "İsmail Karslı ඞ" ***@***.***>:

**Comment by ismailkarsli** [comment]
I got the messages about 2-3 hours later. I guess it was a temporary problem.
