### ISSUE TITLE
Allow creating magazines with CLI

### ISSUE THREAD

**Issue by HelgeKrueger** [MbinOrg/mbin#1200]
In the [first setup instructions](https://docs.joinmbin.org/admin/running-mbin/first_setup), it is written that

> Next, log in and create a magazine named random to which unclassified content from the fediverse will flow.

It would be nice if one could do this from the command line, e.g.

> php bin/console mbin:magazine:create random random

I need this for including mbin in https://data.funfedi.dev and subsequently at the support tables at funfedi.dev.

**Comment by BentiGorlich** [comment]
I absolutely agree. This will be added soon 👍
