### ISSUE TITLE
Adjust valuation of threads to fit with Lemmy

### ISSUE THREAD

**Issue by BentiGorlich** [MbinOrg/mbin#127]
**Is your feature request related to a problem? Please describe.**
In the "hot" category the current system works for me, although "boosts" are a lot more important than just upvotes, but I gues the amount of comments is relevant as well. However in the "top" category it just doesn't work. As far as I can tell it only values boosts and ignores comment count and upvotes, which just hides basically all lemmy posts, as they only upvote.

**Describe the solution you'd like**
Replace boosts with upvote in the valuation formular

**Describe alternatives you've considered**
Add upvotes to the evaluation formular

**Comment by BentiGorlich** [comment]
Ok so now I looked at the code for about two hours. There are a lot of confusing things. First of all the explanation of the sort options:
- top: sorts by the `score` column
- hot: sorts by the `ranking` column
- active: sorts by the `last_active` column
- commented: sorts by the comment count
(see `EntryRepository::filter`)

explanation of the columns:
- `score`: pure `upvotes - downvotes`
- `ranking`:  complicated value computed by the `RankingTrait` that takes the date of the post into account, the newer the better
- `last_active`: as far as I can tell it is just the most recent interaction of any kind

So far it kinda makes sense, if it were'nt for the simple fact that posts that mainly interacted with lemmy simply don't show up in the `top` sort. And I think I found the reason for it: an up vote on lemmy is not an up vote on mbin, but it also isn't a boost on mbin...
The terminology here is the most confusing I've had in a while...

| In the UI | In the Code | From Lemmy | 
| -- | --- | --- |
| Up vote | Favorite | Upvote |
| Downvote | Downvote | Downvote |
| Boost | Up Vote | Doesn't Exist |

And there we have the reason why none of the posts from lemmy are present in the top sort: they all have next to zero up votes, because all lemmy users can do in a mbin DB is favourite a post as down votes are not beeing federated.

**Comment by BentiGorlich** [comment]
The solution is rather easy, however all the `ranking` and `score` columns would need to be updated after the formular is changed, otherwise only posts that get interacted with after the update have the correct score and ranking. That will be a long running migration...

**Comment by e-five256** [comment]
> otherwise only posts that get interacted with after the update have the correct score and ranking. That will be a long running migration...

Is it necessary to? How often do threads 1w/1mo/1y need to show up on the front pages of different rankings (as the threads would still be there, just might need to navigate to them or find them via other methods like newest/search)

**Comment by BentiGorlich** [comment]
> > otherwise only posts that get interacted with after the update have the correct score and ranking. That will be a long running migration...
> 
> Is it necessary to? How often do threads 1w/1mo/1y ago need to show up on the front pages of different rankings (as the threads would still be there, just might need to navigate to them or find them via other methods like newest/search)

I think I might have overreacted, as the correct number of favourites and up votes does exist, the score is only calculated weird. The migration I wrote in #197 will not run that long (I think).
