### ISSUE TITLE
PeerTube Intergration

### ISSUE THREAD

**Issue by SamXavia** [MbinOrg/mbin#162]
**Is your feature request related to a problem? Please describe.**
You can follow PeerTube users on Mbin but can not see Videos released by that user.

**Describe the solution you'd like**
A place for PeerTube Videos to be watched, liked, commented on... ext. (This doesn't have to be for uploading but would be a cool bonus feature that could be turned on by admins)

**Describe alternatives you've considered**
I questioned if Mbin / Kbin are trying to be a hub for the Fediverse or at least a place to look at content both text and image, other alternative solutions could be to simply do a "THIS USER HAS JUST POSTED" update on the Microblog but it would then just redirect you to PeerTube.

**Additional context**
I questioned if Kbin/Mbin was trying to be a one-stop-shop in this post: https://kbin.run/m/AskKbin@kbin.social/t/134071/Is-Kbin-trying-to-be-a-one-stop-shop-for-the#entry-comment-1521351

**Comment by BentiGorlich** [comment]
I just tried following a channel from tilvids on my instance and that worked flawlessly. The channel is recognized as a magazine, so lets see how it looks when the channel posts something :D
I also followed the account, but I don't think that I'll see something there...

**Comment by melroy89** [comment]
I never tested PeerTube to be honest. I did a small curl check in my terminal to see which type this is (so it's a AP "Group" type, which is the same as a magazine indeed in Mbin terms). Not sure how we can distinguish between this PeerTube group and a Magazine/Community group that Mbin/Kbin/Lemmy understands. We could extend Mbin to have dedicated support for Magazines, Videos and microblogging in that case (if that is what we want..??).

Example:

```json
curl -H 'Accept: application/activity+json' https://movies.metricsmaster.eu/c/elektronika/videos | jq


{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    {
      "RsaSignature2017": "https://w3id.org/security#RsaSignature2017"
    },
    {
      "pt": "https://joinpeertube.org/ns#",
      "sc": "http://schema.org/",
      "playlists": {
        "@id": "pt:playlists",
        "@type": "@id"
      },
      "support": {
        "@type": "sc:Text",
        "@id": "pt:support"
      },
      "icons": "as:icon"
    }
  ],
  "type": "Group",
  "id": "https://movies.metricsmaster.eu/video-channels/elektronika",
  "following": "https://movies.metricsmaster.eu/video-channels/elektronika/following",
  "followers": "https://movies.metricsmaster.eu/video-channels/elektronika/followers",
  "playlists": "https://movies.metricsmaster.eu/video-channels/elektronika/playlists",
  "inbox": "https://movies.metricsmaster.eu/video-channels/elektronika/inbox",
  "outbox": "https://movies.metricsmaster.eu/video-channels/elektronika/outbox",
  "preferredUsername": "elektronika",
  "url": "https://movies.metricsmaster.eu/video-channels/elektronika",
  "name": "elektro",
  "endpoints": {
    "sharedInbox": "https://movies.metricsmaster.eu/inbox"
  },
  "publicKey": {
    "id": "https://movies.metricsmaster.eu/video-channels/elektronika#main-key",
    "owner": "https://movies.metricsmaster.eu/video-channels/elektronika",
    "publicKeyPem": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw8U/Rn/t+PlrWQOeOHu4\n2PsoeAeq9XVYv3a+J3rm4kHDJyvO2/dAfapQF4DM9g12WBBeN6L0/ld0rNjUlq1r\n2Dfv72xPMYMHyA/Z4S42AQ4OSbafpiycf8i5gFITAm1iIabmBdXUlBduO+fhDewt\nixa4Aa1E/aCUl+Ym2ua4kGFqUzIPad472HzRPGNMaFY6J2NCPbhS5V3I6lUa3OUd\nnl6reTmtxH9PAUmxliELhK3TuehWlaM05tjlFpLdXsM18acLhXfoUkZs2SFpNIOG\nn17RWnUhGVU1IvAAA21tjfyuRevAXA8j60bnFGLGs1wTqdXhhwzSwRK3TjqZPbqO\nFQIDAQAB\n-----END PUBLIC KEY-----\n"
  },
  "published": "2023-10-28T19:49:29.530Z",
  "summary": null,
  "support": null,
  "attributedTo": [
    {
      "type": "Person",
      "id": "https://movies.metricsmaster.eu/accounts/root"
    }
  ]
}
```

**Comment by BentiGorlich** [comment]
The question that came to my mind was: what happens when one posts to a peer tube channel "group" actor as if it were a magazine?

**Comment by melroy89** [comment]
> The question that came to my mind was: what happens when one posts to a peer tube channel "group" actor as if it were a magazine?

If you post a thread or a blog-post to the group actor, I guess it's being ignored by PeerTube, but you can try it :P...  The videos are of type "Video" btw. As far as I know we do not yet support "Video" types in Mbin. I think we should.. 👍🏽
