### ISSUE TITLE
Castopod Integration

### ISSUE THREAD

**Issue by erlend-sh** [MbinOrg/mbin#166]
https://castopod.org is a PHP-based apub app for Podcasters.

What if Castopod users had a turn-key way of supplementing their podcast with a threadiverse presence via mbin?

cc @yassinedoghri & @benjaminbellamy

**Comment by melroy89** [comment]
Ps. you removed the tempting.. I'm considering closing it and use the provided issue template.

**Comment by melroy89** [comment]
We indeed disabled discussions, since discussions are taking place on matrix. We didn't want to have other places to check as a community.

**Comment by BentiGorlich** [comment]
I don't exactly get what the issue here is. If Castopod is already using AP is something in combination with it not working? And if something is not working, can you link a castopod instance where some activity pub responses can be tested?
