### ISSUE TITLE
Enhancements to account deletion

### ISSUE THREAD

**Issue by e-five256** [MbinOrg/mbin#191]
**Is your feature request related to a problem? Please describe.**

Right now account deletion is a manual process for administrators. A request to delete sends a one-time email to administrators. It's also a confusing process for users, not knowing if their account deletion request is still in-progress or simply missed.

**Describe the solution you'd like**

I think there are many steps to improving the flow that can be broken up into smaller enhancements step-by-step:

1. Move the account deletion button off the general settings page, maybe onto an Account section
   - The account deletion button should be in a less traffic-y area. I believe most users would expect the save button to be the last button when editing their general settings, and would click quickly without reading in some cases
2. Make the delete account section even more "danger"-y
   - It is a danger button, but it could be enhanced with an entire danger zone (take github as an example)
3. Do not allow account deletion if user moderates magazines (similar to github again, can't delete without handing off)
4. Require the user's password and, potentially, 2fa if enabled, when requesting account deletion
   - Feels insecure to simply be a confirm button, allowing anyone with a browser session open to request account deletion
5. Log out the user after submitting a deletion request
   - Don't see a reason the user needs to be logged in after submitting a deletion request
---
6. Create persistence on account deletion
   - Persist the request in some way rather than email, such as a column on the user `marked_for_delete timestamp` or a table to its own
7. Potentially, set the above in the future (say 7 days) and allow the user to log back in to clear it
   - If this seems reasonable, let the user know this option exists in case they change their mind
8. Automate deletion of accounts with the persisted timestamp in the past
   - This one is a bit open ended. Maybe simply having a `Command` that can be called on a cron is good enough

**Describe alternatives you've considered**

All of these suggestions can have alternatives or perhaps not be implemented at all, so welcome any discussion. For instance:

(1) Maybe we can make accidents less likely to happen without moving it via danger zone.
(3) Maybe we're ok with moderator account deletions and it can be folded back to the admin.
(4) Maybe requiring password/2fa is more than necessary, but something like typing the word "delete" would be acceptable to allow the user to know they aren't simply agreeing to saving settings.

Also everything after the horizontal line is a big architectural change, so if people see different or want different changes, potentially only parts of this can be taken for inspiration of changes

**Comment by BentiGorlich** [comment]
Imo it should not be a request, it should be a "I delete my account" action. Nothing that an admin has to worry about. Furthermore it should soft delete instantly (when allowed) and after 30 days or so hard deleted (as in not recoverable), like Mastodon is doing it.

**Comment by melroy89** [comment]
Indeed, this should not be a request. If the user wants to remove the account, the account should be removed directly. Sure, ask the user one more time "Are you sure!?" pop-up. But after a double confirmation from the user, the user needs to be removed (without admin approval).

If this is not happening right away (like we have now), _we are violating GDPR at this moment!!_

**Comment by BentiGorlich** [comment]
As an admin you do have 2 options:
- purge account: delete everything the user wrote and every answer from every user to it
- remove account: delete everything the user wrote, but keep the answers to it

I have to say that neigher of those options sounds ideal if a user deletes their account. With which option should we go? Or do we make a third option and if so what is it?

**Comment by e-five256** [comment]
I wasn't intending it to be a "request" as in the admin has to "allow" you to delete, only in that:
- Sometimes people go through emotional periods and make a mistake (thank goodness my location has buyer's remorse laws, it has saved me many times)
- If there is an easy attack vector, people will go after it to silence those they dislike

I'm not a lawyer of course, and am not giving legal advice. I had to implement GDPR/CCPA, and that included things such as identity verification for deletion to be processed. You can imagine in some places where people have an effect, like say raising awareness to issues, there will be those that attempt all they can to silence it. Of course I'm not trying to imply users should be forced to cough up their last years tax returns, but I think some basic validation and verification that a request did come from them and that there is a method to reverse it is important.

**Comment by BentiGorlich** [comment]
I just meant it as a reference to how it is now.

A verification layer might indeed be very useful. The only thing we have is an email and that is good enough, we don't need more. And of course password/2fa validation is a method as well, maybe combined, maybe just a notification email, dunno

**Comment by e-five256** [comment]
Email verification in unrelated to what I was attempting to describe. All I was saying was, when someone goes to delete their account, they should be able to provide their current password (same as they have to when changing password or changing their email) to prove it is them at their PC/phone.

I also feel like these discussions have been focused on backend only, when I was also trying to bring up the frontend experience for the user, perhaps that should be broken out into a different issue, as I think there's a lot of work here and I'm not sure how to get discussion on all of it to see which parts people agree with for work to be broken up and started.

**Comment by melroy89** [comment]
@e-five256 I personally fully agree on all your stands here. So no worries from my side.

1. Rename "request account deletion" to "Delete my account" on the profile setting page.
    - This also includes; removing the text "The administrator will be notified that you want your account deleted."
2. Introduce a password field that checks the DB with the current password (similar like when changing your email)
3. After user confirmation by the second pop-up screen, delete the user account right away, incl. all of his posts/comments/threads of this user. With the exception maybe of the magazines the user is owner of, since I can understand that people might not be happy to see the magazine getting removed, which was used by others. 

Feel free to split up this work and create PRs from it. My approach is always try to tackle the problem in sub-problems and solve one thing at a time. Ignore the magazines for now for instance and focus first on the actual account deletion instead of request. Then a follow-up PR can further improve the workflow. Same for the frontend, just leave it at settings for now and in another PR you can move the option to another menu. Or you first fix the frontend and then later improve the backend. I leave it up to the community, I just want to share my experience and how I normally tackle these kind of  changes.

**Comment by e-five256** [comment]
For documentation sake (for those outside matrix), kbin made some changes revolving around account deletion here https://codeberg.org/Kbin/kbin-core/pulls/1209

As mbin still is aiming to stay in sync with kbin, some of this may change the priorities / requirements of this issue, depending on what is brought over / changed
