### ISSUE TITLE
Cross-Post Mergers

### ISSUE THREAD

**Issue by SamXavia** [MbinOrg/mbin#194]
**Is your feature request related to a problem? Please describe.**
People often cross-post news between different Magazines these can fill up your feed with 2-5 of the same post, all at the same time.

**Describe the solution you'd like**
Something like a merger for the posts would allow users to still have the post come up but also stop from having your feed filled with duplicate content.

**Describe alternatives you've considered**
Maybe having it so it detects the same content and make it have both Magazines as apart of the description for one and remove the other.

**Comment by melroy89** [comment]
We can fetch the changes from https://codeberg.org/Kbin/kbin-core/pulls/1211 

And this other PR that doesn't say anything but is related to cross-posting: https://codeberg.org/Kbin/kbin-core/pulls/1213

**Comment by melroy89** [comment]
Granted Ernest did try to sabotage us.. https://karab.in/m/karabin/p/340377/Usterka-z-crosspostami-nie-zawsze-sa-przyporzadkowane-odpowiedniemu-watkowi-matce-at-ernest But that should be solved again soon.
