### ISSUE TITLE
Does not follow users from bird.makeup 

### ISSUE THREAD

**Issue by CocoPoops** [MbinOrg/mbin#222]
**Describe the bug**
when trying to follow a user from bird.makeup it can see the user but does not get profiles images or actually follow them as seen on their page on bird.makeup 
https://bird.makeup/users/_coco_poops 

**On which Mbin instance did you find the bug?**
mbin.cocopoops.com running commit [5a3b854] current latest
fedia.io

**To Reproduce**
1. Search for user on mbin eg @_coco_poops@bird.makeup
2. Notice that the profile images arent gotten
3. click on follow 
4. user shows as followed 
5. follow doesn't show on https://bird.makeup/users/_coco_poops

**Expected behavior**
Profiles Image to show correctly and follow to work 

**Screenshots**
![image](https://github.com/MbinOrg/mbin/assets/7891055/d86a2b70-aeb2-478a-a669-47ca7ca0506e)
![image](https://github.com/MbinOrg/mbin/assets/7891055/0064da72-ed25-4c46-9679-226577a425f0)

**Additional context**
also tested this on Mastodon on linuxrocks.online and it works just fine there 
https://linuxrocks.online/@_coco_poops@bird.makeup

**Comment by kreynen** [comment]
Is this the same problem reported at https://codeberg.org/Kbin/kbin-core/issues/1140 ?

**Comment by CocoPoops** [comment]
Closing this as this is working now 
seems to be something that was broken on their end 
https://todo.sr.ht/~cloutier/bird.makeup/3
