### ISSUE TITLE
Regularly fetch remote actors

### ISSUE THREAD

**Issue by BentiGorlich** [MbinOrg/mbin#289]
**Is your feature request related to a problem? Please describe.**
An actor is only refreshed when someone searches for it. We should have a way of regularly doing that, without user interaction

**Describe the solution you'd like**
fetch an actor if it was last fetch >1 day ago and the actor is accessed.
So when I click on a magazine and it is a remote one and the last fetch date is one week ago: dispatch a `UpdateActorMessage`

**Describe alternatives you've considered**
none

**Additional context**
#235

**Comment by e-five256** [comment]
All actors, or just ones linked by /moderators in groups for magazine info? My fear with all actors is the large majority will just be inactive accounts, which will only grow with time

**Comment by BentiGorlich** [comment]
My idea was to fetch an actor if it was last fetch >1 day ago and the actor is accessed.
So when I click on a magazine and it is a remote one and the last fetch date is one week ago: dispatch a `UpdateActorMessage`. This would work with users and inactive accounts are rarely accessed I'd say

**Comment by e-five256** [comment]
I imagine there has to be some update that isn't solely when searched: I mentioned recently I set my avatar on an instance, it didn't appear on another for a day, but then when I upvoted something the next day it instantly got my avatar, so I imagine sending a new AP event also updates actor info?

**Comment by BentiGorlich** [comment]
Ok, here are my final findings: 
- user actors are updated when the post something, follow something, or do anything in general (I think)
- magazines were only updated when the announced something, because they then were the `actor` in these messages and were updated accordingly. 

I implemented a fetch of them when something is posted to them in https://github.com/MbinOrg/mbin/pull/235
