### ISSUE TITLE
Emojis aren't rendered

### ISSUE THREAD

**Issue by LoveIsGrief** [MbinOrg/mbin#350]
**Describe the bug**

**On which Mbin instance did you find the bug?**

fedia.io

**To Reproduce**
1. Got to https://lemmy.world/comment/6084307
2. Open https://fedia.io/search?q=https%3A%2F%2Flemmy.world%2Fcomment%2F6084307 in a new tab
3. Compare the two

**Expected behavior**

Smiley's should be rendered

**Screenshots**

Lemmy

![image](https://github.com/MbinOrg/mbin/assets/2829538/38216760-3393-4fa4-b1b3-a0738a04ee4d)

Mbin

![image](https://github.com/MbinOrg/mbin/assets/2829538/bd46fbeb-1299-4b30-ba57-a709bfe2a763)

**Desktop (please complete the following information):**
 - OS: NixOS 23.05
 - Browser Firefox
 - Version 120.0 (64-bit)

**Additional context**

Also tried on Chromium, with the same result

**Comment by e-five256** [comment]
Just to double check, I opened the fedia link you posted and see the smiley, do you also see it now? I believe you screenshot, I wonder if it was edited in and the edit took a bit, or something else

**Comment by LoveIsGrief** [comment]
What do you mean by "edited in". It reads like you think I edited the picture to remove or add the emoji...

**Comment by LoveIsGrief** [comment]
Oh, I interpreted your comment incorrectly :pray: 

I had a look at the HTML and the smiley is there

![image](https://github.com/MbinOrg/mbin/assets/2829538/44035528-211b-43e5-a895-7fb113a62195)

After having a look at the CSS, it's the font family that's the problem.

After disabling `body { font-family: var(--kbin-body-font-family); }`, I see the smiley.

**Comment by e-five256** [comment]
This sounds related to #257

**Comment by LoveIsGrief** [comment]
Removing `system-ui` doesn't fix it, but removing `"Noto Color Emoji"` does.

Might be related to https://github.com/googlefonts/noto-emoji/issues/266

Maybe for now we could just remove `"Noto Color Emoji"` from the `font-family`. Lemmy doesn't use it either and it works fine for me.

**Comment by e-five256** [comment]
Can you see if

```
-apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
```

works for you? I think that is the one I will suggest. Mainly based off github/wordpress which appears to be what everyone follows. I would've liked to add `Ubuntu` to that as it seems to make the site not look worse for me, but I can't find any examples of people using it besides a blog from 2016 so don't want to risk it if it causes issues

**Comment by LoveIsGrief** [comment]
That works for me! @e-five256

**Comment by nobodyatroot** [comment]
This issue has been resolved by https://github.com/MbinOrg/mbin/pull/257, confirmed the linked post in the issue now renders the emoji correctly: https://kbin.run/m/technology@lemmy.world/t/178598/Worst-person-in-tech-2023-semi-final#entry-comment-1962480
