### ISSUE TITLE
Enhance information in magazine overview

### ISSUE THREAD

**Issue by BentiGorlich** [MbinOrg/mbin#362]
**Is your feature request related to a problem? Please describe.**
One cannot know whether a remote magazine gets updates, because there is no way to see whether a magazine has local subscribers. Additionally it is not obvious how old the displayed information (subscriber count, description, moderators, etc.) is.

**Describe the solution you'd like**
1. show an information that the info not up to date when it is older than a day. 
2. show an information that the magazine won't get any updates because no one on the instance is subscribed

hints:
1. There is a column in the database that contains the last fetched datetime
2. When the magazine_subscriptions table does not contain a local subscription for the magazine show the warning that it will not get updates

**Comment by e-five256** [comment]
I mentioned in matrix but adding to here as well:

1. seems fairly straightforward as it's just hooking up the frontend to backend data we have
2. this however seems a bit more complicated; from my understanding we lost local subscriber counts when we set the column data to use the count from the source. There are a few ways we could go about this but likely I think we'd just want to recreate a `local_follower` column or something, adding and subtracting every time a local sub/unsub or follow/unfollow happens, with a one time migration of reading the subscription table and setting the column values to current count. Reasoning being that we wouldn't want to seq scan the subscription table every time we need this information

not sure if that means this could be broken up into multiple issues, or even if not they could probably be handled in separate PRs

**Comment by e-five256** [comment]
Just wanted to double check on whether this is complete, or if there is still more work to do

I see the two points listed in the OP on magazines now

![image](https://github.com/MbinOrg/mbin/assets/146029455/63c24b96-408d-4457-8fb7-1ecad5bbbdf3)

But not sure if there's remaining work or it needs some polish passes

**Comment by BentiGorlich** [comment]
You're right this was done via #436
