### ISSUE TITLE
More than one record returned causes error 500

### ISSUE THREAD

**Issue by Jerry-infosecexchange** [MbinOrg/mbin#38]
I get this error on my "people" page at: https://fedia.io/people - this was happening befoe and after moving from kbin to mbin.  Any ideas on what records are at fault?  

```
[2023-10-14T20:05:05.304076+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Error rendering "user_box" component: An exception has been thrown during the rendering of a template ("More than one result was found for query although one row or none was expected.")." at /var/www/kbin/templates/people/front.html.twig line 39 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Error rendering \"user_box\" component: An exception has been thrown during the rendering of a template (\"More than one result was found for query although one row or none was expected.\"). at /var/www/kbin/templates/people/front.html.twig:39)\n[previous exception] [object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"More than one result was found for query although one row or none was expected.\"). at /var/www/kbin/templates/components/user_box.html.twig:36)\n[previous exception] [object] (Doctrine\\ORM\\NonUniqueResultException(code: 0): More than one result was found for query although one row or none was expected. at /var/www/kbin/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:967)"} []
```

**Comment by melroy89** [comment]
be sure to run: `./bin/post-upgrade` script.

**Comment by Jerry-infosecexchange** [comment]
I have and it's completed cleanly

**Comment by melroy89** [comment]
I see. Do you have PHP OPcache enabled? If so, try to reload PHP-FPM service. If that also doesn't work, we need to dive a bit deeper into the code. And find the root-cause asap.

**Comment by Jerry-infosecexchange** [comment]
I did a full on reboot and also tried restarting php, but yes, I do have opcache enabled.  

There is some history here - when I first set up the instance, I had it running as the containerized deployment.  The load quickly went past what the server could handle and I moved to bare metal.  After dumping the database and reloading it on a new server, everything work at first, but then I started getting an increasing number of errors that were mainly because of key constraint violations.  The most common one has been magazines, users, posts, and other records getting assigned an image ID, however no image record exists with that id, and so the whole system tanks.  

I have that problem more or less mitigated through a cron job that looks for records of various types with missing image ids, and I blank those out.  That fixed 95% of the issues, though it's still happening and I've never figured out why.  

This issue seems similar.  I also have an example of a user account (https://fedia.io/u/stack)  that throws an error 500, though I don't see any errors in prod.log associated with it.

In any event, focusing on the people problem, I'd like any suggestions on how to debug.

**Comment by melroy89** [comment]
In Mbin we now also show Local Users when no about field is set.

The exception is a Doctrine\ORM\NonUniqueResultException, which is thrown when a query returns more than one result when one row or none was expected.

It's happening in the `user_box.html.twig` template file (located at: `templates/components`). On Line 36:
```
                    {{ user.about|markdown|raw }}
```

You can try to dump the var using: https://symfony.com/doc/4.1/templating/debug.html

Use the dump() function to print out the values of variables in your templates.  Maybe that help us understand what is happening here. 

I did notice just now there can be an improve on line 33 of the `user_box.html.twig` I think the if check should be something like: `{% if user.about | length > 0 %}` Not sure if that actually fixes your issue.

**Comment by melroy89** [comment]
Alternatively, you can also debug the variable `user` in the `front.html.twig` template file on line 39  (located at: `templates/people`). I know this code is trying to point and render this user_box component. But it would be interesting to if you could dump() the `user` variable.  And inspect what the hack is going on with this specific user (or users) and their about field.

**Comment by melroy89** [comment]
OK, we discussed in Matrix, there is something wrong the content of the about of this user "stack". Why is still unknown.

**Comment by melroy89** [comment]
OK maybe... it's the markdown Twig parser or the `raw` thingy. Or we might still blame PostgreSQL v5.

**Comment by asdfzdfj** [comment]
found some potential leads: [1] [2] [3] [4] 

could you run these sql commands on your database and see if anything comes up?

```sql
select id, username, lower(username) as username_lower, ap_id, ap_profile_id from "user"
where lower(username) in (
    select lower(username) from "user" group by lower(username) having count(*) > 1
) order by id desc;
```

```sql
select id, name, lower(name) as lower_name, ap_id, ap_profile_id from magazine
where lower(name) in (
    select lower(name) from magazine group by lower(name) having count(*) > 1
) order by id desc;
```

[1]: https://github.com/MbinOrg/mbin/blob/809c8961b0c663a9532462c5100e9d7a149a4608/src/Repository/UserRepository.php#L276-L283
[2]: https://github.com/MbinOrg/mbin/blob/809c8961b0c663a9532462c5100e9d7a149a4608/src/Repository/MagazineRepository.php#L64-L73
[3]: https://github.com/MbinOrg/mbin/blob/809c8961b0c663a9532462c5100e9d7a149a4608/src/Markdown/CommonMark/CommunityLinkParser.php#L44
[4]: https://github.com/MbinOrg/mbin/blob/809c8961b0c663a9532462c5100e9d7a149a4608/src/Markdown/CommonMark/MentionLinkParser.php#L118-L154

**Comment by Jerry-infosecexchange** [comment]
The first query returned perhaps thousands of records - haven't figured a way to count.  The second one returns two records.

**Comment by Jerry-infosecexchange** [comment]
interesting...
kbin=# select id, username, lower(username) as username_lower, ap_id, ap_profile_id from "user"
where lower(username) = '@stack@fedia.social'
;
   id   |      username       |   username_lower    |       ap_id        |                ap_profile_id
--------+---------------------+---------------------+--------------------+---------------------------------------------
 318051 | @stack@fedia.social | @stack@fedia.social | stack@fedia.social | https://fedia.social/users/9ktvxebzh9f0sovo
 318050 | @stack@fedia.social | @stack@fedia.social | stack@fedia.social | https://fedia.social/users/9ktvxebzh9f0sovo
(2 rows)

**Comment by melroy89** [comment]
There is the duplicated record. With the same username, but most likely due to case insensitive invested despite a unique check in the db.

We might want to lowercase everything before checking / inserting users.

**Comment by Jerry-infosecexchange** [comment]
I neglected to post this:
kbin=# select count(*) from "user"
where lower(username) in (
    select lower(username) from "user" group by lower(username) having count(*) > 1
);
 count
-------
 55623
(1 row)

**Comment by asdfzdfj** [comment]
oof, that seems rough, I was kind of expecting something like `@stack@fedia.social` and `@Stack@fedia.social` and not something that looks like identitcal record duplication where the unique constraints somehow doesn't apply like in here (IIRC there're on `username`, `ap_id`, and `email` fields for `"user"` table, could you select all fields and compare them? I have a bad hunch that it'll be identical, and do tell if it's not the case).

---

> There is the duplicated record. With the same username, but most likely due to case insensitive, despite the db having a unique check on the column.
> 
> We might want to lowercase everything before checking / inserting users.

I think that's a worthwhile discussion to be have, but I don't think it applies here. there seems to be something _really_ wonky going on in Jerry's database. how did it ended up in this state in the first place?

**Comment by Jerry-infosecexchange** [comment]
`how did it ended up in this state in the first place?`
I ask myself this every day.  For these duplicate records, my best hypothesis is that the instance was accepting federation as both "www.fedia.io" and "fedia.io", despite having defined only "fedia.io" as the domain in the .env config file.  I think I should be able to test this hypothesis to confirm that no recent accounts are duplicated since I changed nginx to handle www differently

**Comment by Jerry-infosecexchange** [comment]
This is all I have:

Indexes:
    "idx_8d93d64986383b10" btree (avatar_id)
    "idx_8d93d649922726e9" btree (cover_id)
    "user_id_key" UNIQUE CONSTRAINT, btree (id)
Referenced by:
    TABLE "oauth2_client" CONSTRAINT "fk_669ff9c9a76ed395" FOREIGN KEY (user_id) REFERENCES "user"(id)
    TABLE "oauth2_user_consent" CONSTRAINT "fk_c8f05d01a76ed395" FOREIGN KEY (user_id) REFERENCES "user"(id)

**Comment by Jerry-infosecexchange** [comment]
I see that Version20220911120737.php created the index you're referring to.  I am not sure how or why that wouldn't be present, given that was from 2022 and I didn't install kbin until March or April of 2023

**Comment by Jerry-infosecexchange** [comment]
Right. I set this up initially using the container-based kbin setup, but it quickly exceeded the capacity of running on a single host. From there, I dumped the database and imported it into a database on a dedicated server and moved to bare metal from there. What is odd is that those changes should already have been in place at the time I set up the instance initially, unless there was an issue with the docker setup. Which seems not impossible in hindsight. Do you see any options other than my picking through the migrations to see what is missing and manually apply them?

**Comment by melroy89** [comment]
Well.. The answer I give you now is not helpful, but there is a `./bin/console doctrine:migrations:diff`, but it gives me an error on this `user_type`:  `Unknown database type user_type requested, Doctrine\DBAL\Platforms\PostgreSQL100Platform may not support it.` Which is strange, since this is an enum type, but doctrine do not get it!? 

https://github.com/doctrine/dbal/issues/3161#issuecomment-391682594 (saying that enum type is a custom type, while actually it's not really a custom type, it's just a built-in feature of PostgreSQL)

**Comment by melroy89** [comment]
OK. I added support for this `user_type` and mapped it just to string (I don't want to declare a custom enum type entity), this will fix the `doctrine:migrations:diff` command again: https://github.com/MbinOrg/mbin/pull/110

**Comment by Jerry-infosecexchange** [comment]
Well, I backed up my database and went for it.  It looks like there are some inconsistencies.  This is an entry with a user_id reference that doesn't exist in the user table.  I suspect I am in for a data cleaning party.  
```
kbin@php:/var/www/kbin$ ./bin/console doctrine:migrations:migrate

 WARNING! You are about to execute a migration in database "kbin" that could result in schema changes and data loss. Are you sure you wish to continue? (yes/no) [yes]:
 > yes

[notice] Migrating up to DoctrineMigrations\Version20231024102758
[error] Migration DoctrineMigrations\Version20231024102758 failed during Execution. Error: "An exception occurred while executing a query: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "entry" violates foreign key constraint "fk_2b219d70a76ed395"
DETAIL:  Key (user_id)=(57482) is not present in table "user"."
10:42:42 CRITICAL  [console] Error thrown while running command "doctrine:migrations:migrate". Message: "An exception occurred while executing a query: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "entry" violates foreign key constraint "fk_2b219d70a76ed395"\nDETAIL:  Key (user_id)=(57482) is not present in table "user"." ["exception" => Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException^ { …},"command" => "doctrine:migrations:migrate","message" => """  An exception occurred while executing a query: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "entry" violates foreign key constraint "fk_2b219d70a76ed395"\n  DETAIL:  Key (user_id)=(57482) is not present in table "user".  """]

```

**Comment by melroy89** [comment]
But yes I think the generated doctrine diff migration should be ran in order to clean up the differences.

**Comment by Jerry-infosecexchange** [comment]
Do you have any recommendations for clearing out the "orphaned" records, like the one above?  The obvious answer is to delete the entry, but I expect that will cascade to other dependencies like entry_comments, votes, favourites, and so on

**Comment by e-five256** [comment]
Wanted to check in and see if this could now be closed. Of course, I don't think we got to the root of the issue in how this happened in the first place, but I'm not sure we'll be able to figure that out exactly. It seemed like the answer to this was a db schema with missing unique constraints, and it was fixed by rebuilding the db.

**Comment by nobodyatroot** [comment]
Result of a bad migration, issue has since been resolved.
