### ISSUE TITLE
Blocked users still show notifications on replies

### ISSUE THREAD

**Issue by LoveIsGrief** [MbinOrg/mbin#405]
**Describe the bug**
A copy of the [same bug on kbin](https://codeberg.org/Kbin/kbin-core/issues/828) which @e-five256  opened.

After blocking a user, you will still receive notifications that they have replied to your posts (along with a preview of what they said). Clicking on the notification will bring you to the thread but not display the message.

**On which Mbin instance did you find the bug?**

fedia.io

**To Reproduce**
1. Comment on a user's post or comment
2. Block the user
3. Wait for their response
4. It will show up in your notifications

**Expected behavior**

Blocked users shouldn't be able to trigger any notifications whatsoever.

**Screenshots**

`-`

**Desktop (please complete the following information):**
 - OS: NixOS 23.11
 - Browser Firefox
 - Version 121

**Additional context**

**Comment by LoveIsGrief** [comment]
Spectacular! Thank you 💌

**Comment by BentiGorlich** [comment]
You're welcome :innocent:
