### ISSUE TITLE
go to comment doesn't work / Notification link is unaware of pagination

### ISSUE THREAD

**Issue by LoveIsGrief** [MbinOrg/mbin#406]
**Describe the bug**
A copy of the [bug on kbin](https://codeberg.org/Kbin/kbin-core/issues/370)

> When there is a reply to a comment of mine, I clicked on the notification. But the link goes to page 1.. While the reply is on page 2.
>
> Kbin notification link is: https://kbin.melroy.org/m/RedditMigration@kbin.social/t/9/23k-New-Lemmy-and-Kbin-Accounts-Created-in-Last-Hour#entry-comment-203 (which is incorrect).
>
> Since the comment in on the 2nd page. The notification link should have been: https://kbin.melroy.org/m/RedditMigration@kbin.social/t/9/23k-New-Lemmy-and-Kbin-Accounts-Created-in-Last-Hour?p=2#entry-comment-203 (notice the ?p2)

Possibly opened by @melroy89 himself.

**On which Mbin instance did you find the bug?**

fedia.io

**To Reproduce**
1. Find a post with more than one comment page
2. Go to comment page 2+
3. Open link to any comment on that page in a new tab

**Expected behavior**

The link should open the post with the comment itself and subcomments (just like on reddit and lemmy).

**Screenshots**

On lemmy  https://hexbear.net/comment/3753319
![image](https://github.com/MbinOrg/mbin/assets/2829538/ee49c15a-3f39-46cd-a9f0-ec41f138724d)

On mbin https://fedia.io/m/meta@lemm.ee/t/215813/Hexbear-federation-megathread#entry-comment-2565198 should show 
![image](https://github.com/MbinOrg/mbin/assets/2829538/a8e41174-0f66-4ed5-bc90-9c2ba887c00b)
 but instead it just shows 
![image](https://github.com/MbinOrg/mbin/assets/2829538/da299c71-26c9-4002-bcee-2a5c7e36844e)

**Desktop (please complete the following information):**
 - OS: NixOS 23.11
 - Browser Firefox
 - Version 121

**Additional context**

Lemmy and Reddit have already solved the problem and probably mbin should follow suit.

**Comment by e-five256** [comment]
I have this in progress https://github.com/MbinOrg/mbin/compare/main...e5/comment-view but am running into a bit of trouble with the children/nested replies to the comment. I put it aside for a bit but will try to circle back to it

(I want the direct replies of the comment you're trying to view to appear, but when I do that, for some reason it starts at the _root_ of the entire thread, which I have no idea how it's even doing. I've dumped out the `children` element and it'll only have, say, 3 elements of the 3 direct replies, but when the twig template uses it it starts at the top 1 reply regardless. Sadly not super knowledgeable of the DTO myself so might need to get some help)
