### ISSUE TITLE
Icon/image type mismatch in magazine test fixture data

### ISSUE THREAD

**Issue by nobodyatroot** [MbinOrg/mbin#42]
In spinning up a mbin dev instance, I'm unable to load the magazine test fixture data due to a type mismatch in the assignment for the magazine icon. I believe this is related to the image handling code that was changed as part of the API implementation.

```
mbin@mbin-dev:~/mbin/docker/v2$ sudo docker compose exec php bin/console doctrine:fixtures:load --append --no-debug
   > loading App\DataFixtures\UserFixtures
   > loading App\DataFixtures\MagazineFixtures

In MagazineFixtures.php line 51:

  Cannot assign App\Entity\Image to property App\DTO\MagazineDto::$icon of type ?App\DTO\ImageDto
```

Relevant code snippet:

```
$image = null;
$width = rand(100, 400);

try {
	$tempFile = $this->imageManager->download("https://picsum.photos/{$width}/?hash=$width");
} catch (\Exception $e) {
	$tempFile = null;
}

if ($tempFile) {
	$image = $this->imageRepository->findOrCreateFromPath($tempFile);
	$this->entityManager->flush();
}

$dto = new MagazineDto();
$dto->name = $magazine['name'];
$dto->title = $magazine['title'];
$dto->description = $magazine['description'];
$dto->rules = $magazine['rules'];
$dto->badges = $magazine['badges'];
$dto->icon = $image;
```

Commenting out the assignment to `$image` thereby keeping `$dto->icon` set to `null` allows all other test fixtures to load successfully, so I believe this is the only test fixture code that needs updating.

**Comment by melroy89** [comment]
Yea so be sure if it is a bug in production or test or both ;). Maybe MagazineDto needs to be updated or findOrCreateFromPath

**Comment by nobodyatroot** [comment]
From what I can tell the test fixtures are disabled in production mode. I was following along with the [CONTRIBUTING.md](https://github.com/MbinOrg/mbin/blob/main/CONTRIBUTING.md#fixtures) file and this step will fail, but I'll add a low priority tag since this is just some filler data for development purposes.

**Comment by melroy89** [comment]
off-topic: You can add yourself to the docker group, so you do not need `sudo docker` but just run `docker`. To add yourself/current user to the docker group, run: `sudo usermod -aG docker $USER`. Then log-out and log-in again ;)
