### ISSUE TITLE
When going to the next page, previous page posts are still visible

### ISSUE THREAD

**Issue by justinfarrelldev** [MbinOrg/mbin#427]
**Describe the bug**

This has been an issue since Kbin launched, so I am pretty sure we have all encountered this. When you get a few pages into the Home feed, the posts start repeating themselves (showing a few of the posts which were in the previous page at the top). 

**On which Mbin instance did you find the bug?**
[kbin.run]

**To Reproduce**
1. Scroll the Home Page. Take note of the posts. 
2. Make sure infinite scroll is OFF. Click through each subsequent next page. 
3. Eventually, you will see posts on the top of the page that were present in the last page.

**Expected behavior**
A new page should have entirely fresh posts.

**Smartphone (please complete the following information):**
 - Device: [Pixel 6 Pro]
 - OS: [Android 14]
 - Browser [using the app Native Alpha but it's visible regardless of browser]
 - Version [unknown]

**Additional context**
This was an issue on Kbin as well, just thought maybe it could be fixed once-and-for-all on Mbin.

**Comment by justinfarrelldev** [comment]
I would like to keep this open, as this is still a concern.

**Comment by nobodyatroot** [comment]
@justinfarrelldev can you try replicating this on an instance running Mbin 1.7.0? i tried to replicate it on kbin.run and i can't seem to get it to do it. we've updated a lot of packages since this issue was opened and i'm curious if it "resolved" itself.

**Comment by justinfarrelldev** [comment]
> @justinfarrelldev can you try replicating this on an instance running Mbin 1.7.0? i tried to replicate it on kbin.run and i can't seem to get it to do it. we've updated a lot of packages since this issue was opened and i'm curious if it "resolved" itself.

I just tried on kbin.run as well, and it appears you are correct! It must have been fixed in the interim somehow 🙂 I haven't used mbin in a hot minute, but I'm glad to hear this was resolved!
