### ISSUE TITLE
Stop federating /m/random

### ISSUE THREAD

**Issue by BentiGorlich** [MbinOrg/mbin#444]
**Is your feature request related to a problem? Please describe.**
Unmoderated content from the random mag is federating to other servers.

**Describe the solution you'd like**
The random mag as the local catch all for posts and entries which can not be put into another magazine should not accept followers and should not announce posts in any way.

**Describe alternatives you've considered**
Don't even return it for the webfinger

**Additional context**

**Comment by asdfzdfj** [comment]
(for the record) appears to be regression/undesired side effects from #369

the person who notices this:
- https://brain.d.on-t.work/notes/9oefk7qy36f804qp
- https://brain.d.on-t.work/notes/9ofjcwde36f808rc

**Comment by nobodyatroot** [comment]
@BentiGorlich This should be resolved now, no?

**Comment by BentiGorlich** [comment]
nope. I only made hotfixes, but if there are users subscribed to the magazine, sfuff still gets federated

Am 4. Februar 2024 04:50:10 MEZ schrieb debounced ***@***.***>:
