### ISSUE TITLE
Accept MBIN_* naming convention in dot env files

### ISSUE THREAD

**Issue by melroy89** [MbinOrg/mbin#45]
We should support for now both `KBIN_*` and `MBIN_*` in the dot env files configuration (eg. in files like: `.env.example`).

Then we should safely change the example files towards "MBIN" as well (used for new server owners). While also supporting existing servers that still running KBIN config files. Meaning we are backwards compatible for the foreseeing future.

This backwards compatibility is important if we want to keep easy migration from Kbin towards Mbin.

**Comment by TheVillageGuy** [comment]
If it's not already the case, I'd suggest replacing all hard coded root pathd with variables

**Comment by BentiGorlich** [comment]
@melroy89 want to reopen this?
