### ISSUE TITLE
Posts with too large images get created as articles

### ISSUE THREAD

**Issue by BentiGorlich** [MbinOrg/mbin#498]
**Describe the bug**
When a remote instance sends a post with an attached image, but the image is too large for our server, it gets created as an article and not as an image. That means, that there is no thumbnail and that there is no preview icon in the post. Basically there is no way of seeing the attached image, other than to go to the original instance

**On which Mbin instance did you find the bug?**
[kbin.melroy.org, fedia.io, gehirneimer.de, rimworld.gallery]

**To Reproduce**

**Expected behavior**
If an image is too big to save it, it should eigher be converted to something smaller or it should not get created at all and instead it should just use / link to the original image

**Screenshots**

**Additional context**
rimworld.gallery uses very high quality images which should get picked up correctly...
@TheVillageGuy feel free to add more information

**Comment by melroy89** [comment]
I mentioned it in the PR, but for full transparency I repeat it here.  Loading content / images from other domains will not always work depending if the server have CSP configured too strictly (for security reasons).
