### ISSUE TITLE
Title bug when hiding post thumbnail and activating Auto media preview 

### ISSUE THREAD

**Issue by Shitsurei-shimasu** [MbinOrg/mbin#499]
**Describe the bug**
Title will change to 1 character per line when hiding post thumbnail and activating Auto media preview 

**On which Mbin instance did you find the bug?**
Kbin.run

**To Reproduce**
1. Go to 'Theme Settings'
2. Activate 'Auto media preview '
3. Deactivate 'Show Thumbnail '

**Expected behavior**
As stated above

**Screenshots**
Attached 

**Desktop (please complete the following information):**
 - OS: android 14
 - Browser Firefox 
 - Version 122.1

**Smartphone (please complete the following information):**
 - Device: pixel 7
 - OS: android 14
 - Browser Firefox 
 - Version 122.1]
![Screenshot_20240216-054248](https://github.com/MbinOrg/mbin/assets/21995163/8c353f3f-f4d9-4449-b993-88db24eeec0d)

**Comment by BentiGorlich** [comment]
I can reproduce it and it should be relatively easy to fix if one knows CSS

**Comment by e-five256** [comment]
It looks like the `preview` grid area is simply missing from the `.no-image` grids
https://github.com/MbinOrg/mbin/blob/8b68bd15694e4e53e6bf1e96b3199074fcad7369/assets/styles/components/_entry.scss#L25-L26
https://github.com/MbinOrg/mbin/blob/8b68bd15694e4e53e6bf1e96b3199074fcad7369/assets/styles/components/_entry.scss#L64-L65

adding it between those lines seemed to have fixed some of the issues for me
