### ISSUE TITLE
Third party login methods allow for new accounts when registration is disabled

### ISSUE THREAD

**Issue by e-five256** [MbinOrg/mbin#518]
**Describe the bug**

Right now third party authentication methods go through a few steps, mainly checking if a user already exists and if not, creating one.

[In between those two steps](https://github.com/MbinOrg/mbin/blob/225a50b9dba9957b7518e250c227df1da6bb815a/src/Security/FacebookAuthenticator.php#L79), they should check if registration is disabled on the site and if so, return an error. This ideally allows users that already have registered to still login, while blocking new users

**On which Mbin instance did you find the bug?**
All

**To Reproduce**
1. Disable registration
2. Attempt to login with facebook/google on a new email address
3. Observe that a new account is created

**Expected behavior**

Registrations being disabled blocking new accounts from being created

**Comment by e-five256** [comment]
Perhaps there's some more discussion to be had on how it should act, looking at an mbin instance that only supports a third party login, it looks like that reports via AP that registration is disabled. I'm not sure if that's accurate compared to how other fediverse software report third party only account registration. Perhaps there should instead be a new env var like "third party registration disabled". The problem I'd like to solve is allow all existing users to continue to use the site, but stop all forms of new account creation.

**Comment by BentiGorlich** [comment]
Imo if registrations are disabled 3rd Party account creation should not work eigher. Imo there should be a separate env var for only allowing registrations via 3rd party providers

**Comment by e-five256** [comment]
I just wanted to make it clear that some instance owners currently rely on disabled account registration env var and accounts to be created successfully via third party systems. Just to loop @thepaperpilot in, since that was the one I observed. Maybe that means it should be a new `native_registration_disabled` or something, but my initial suggestion would break thepaperpilot's instance as new accounts wouldn't work through zitadel 🤔

**Comment by thepaperpilot** [comment]
I can confirm my instance is closed to registrations except through an oauth provider. I rely on accounts being created automatically when logging in through that provider. I'm fine with having multiple env vars though - one for external and one for internal seems fine to me. I'm not sure the use case for wanting to disable it for some but not all oauth providers
