### ISSUE TITLE
Document setup of all possible ID-Providers

### ISSUE THREAD

**Issue by BentiGorlich** [MbinOrg/mbin#570]
**Is your feature request related to a problem? Please describe.**
If an instance admin wants to setup identity providers they have to look at the code to get all the paths they need

**Describe the solution you'd like**
We should have a section in our docs for this

**Describe alternatives you've considered**
none

**Additional context**
#429

**Comment by nobodyatroot** [comment]
likewise, https://docs.joinmbin.org/admin/optional-features/sso good enough or no?

**Comment by nobodyatroot** [comment]
closed in favor of updates to https://docs.joinmbin.org/admin/optional-features/sso

**Comment by BentiGorlich** [comment]
You're absolutely right :+1:
