### ISSUE TITLE
Users created with Authentication Providers can change their username

### ISSUE THREAD

**Issue by BentiGorlich** [MbinOrg/mbin#571]
**Describe the bug**
If you create a user through, Google, Facebook, etc. you can change the username 

**On which Mbin instance did you find the bug?**
[dev instance]

**To Reproduce**
1. Create a user via any identity provider
2. You get the profile settings page where you can just change the username again and again

**Expected behavior**
The username should be set at first login and then be permanent

**Screenshots**
![grafik](https://github.com/MbinOrg/mbin/assets/25664458/a44f07f8-2aa9-4668-ba59-a0a4fc5da7af)

**Additional context**
I noticed it while reviewing #429 

---

The reason this is a problem is very simple: once any remote Activity Pub instances know this user they expect the webfinger to be permanently the same. If it changes the system just doesn't work anymore (think mentions, follows, etc. etc.)

**Comment by melroy89** [comment]
It's not a high prio: it's tackled by this piece of code already (so you are only allowed to change your username if you didn't post, subscribe, etc. yet): https://github.com/MbinOrg/mbin/blob/main/src/Security/Voter/UserVoter.php#L83

Lowering the severity of this issue.
