### ISSUE TITLE
Implement OIDC provider for Microsoft Azure

### ISSUE THREAD

**Issue by WebVoid** [MbinOrg/mbin#575]
**Is your feature request related to a problem? Please describe.**
We are discussing of implementing an Mbin instance in our company to manage our communities and would like to centralize authentication using our Azure tenant

**Describe the solution you'd like**
An Azure OIDC provider with the right env variables to configure it

**Describe alternatives you've considered**
-

**Additional context**
We would be able to implement such solution if accepted

**Comment by e-five256** [comment]
@WebVoid Just want to make sure we're good to close this as complete with your work having been merged

**Comment by e-five256** [comment]
I'm going to assume this is all set with #665, feel free to reopen or make a new issue if you're seeing any problems
