### ISSUE TITLE
Restrict the instance to authenticated users only

### ISSUE THREAD

**Issue by WebVoid** [MbinOrg/mbin#577]
**Is your feature request related to a problem? Please describe.**
We are discussing of implementing an Mbin instance in our company to manage our communities and would like to deny access to any content to unauthenticated users, kind of like a "private" instance.

**Describe the solution you'd like**
When "private" (or whatever) mode is enabled when trying to reach the instance, auto redirect to the login page, allowing only authenticated people to see any content.

**Describe alternatives you've considered**
Protect the whole instance with an OAuth2 proxy, but it would double the need for authentication, once for the proxy and once in the app.

**Additional context**
We would be able to propose a PR if the feature request was accepted.

**Comment by BentiGorlich** [comment]
I honestly don't know how much effort this would be to implement. I sadly do not know symfony all that well in that regard. However I think it is a feature that at the very least doesn't hurt anybody and that can be useful for folks like you. So if you want to implement it, I am all for it :D

**Comment by WebVoid** [comment]
I will take a look at it, I did some symfony some ages ago, I believe the security layer could cover the entirety of the use-case.

**Comment by melroy89** [comment]
This is now resolved with the PR #678 ?

**Comment by WebVoid** [comment]
It is, I will close it, thanks for the reminder
