### ISSUE TITLE
[SQL] Duplicate Favourite Rows

### ISSUE THREAD

**Issue by BentiGorlich** [MbinOrg/mbin#578]
**Describe the bug**
Multiple sql rows for the same user + [entry/entry_comment/post/post_comment] combination

**On which Mbin instance did you find the bug?**
all of them

**To Reproduce**
1. `sudo -u kbin psql`
2. run 
```sql
SELECT entry_comment_id, user_id, COUNT (*) as cnt FROM favourite 
WHERE entry_comment_id IS NOT NULL 
GROUP BY entry_comment_id, user_id 
HAVING COUNT(*) > 1 
ORDER BY cnt DESC LIMIT 1000;
```
3. get a lot of results

**Expected behavior**
This query should yield no results, as the each user can only favourite each entry, entry_comment, post or post_comment exactly once and the code expects this in certain cases which leads to a lot of messenger errors

**What should be done**
write an sql migration which consists of:
- queries to remove duplicates, I found [this post](https://www.postgresqltutorial.com/postgresql-tutorial/how-to-delete-duplicate-rows-in-postgresql/) which outlines how to do that
- create 4 unique indices for these pairs in the favourite table:
  - user_id, entry_id
  - user_id, entry_comment_id
  - user_id, post_id
  - user_id, post_comment_id

This will be a huge migration on production servers, as the favourite table is quite large

Just a note: the 4 vote tables already have an unique index, so there is nothing to do for that

**Comment by BentiGorlich** [comment]
SQL queries that remove duplicates:
```sql
DELETE FROM favourite a USING favourite b WHERE a.id > b.id AND a.entry_id = b.entry_id AND a.user_id = b.user_id;
DELETE FROM favourite a USING favourite b WHERE a.id > b.id AND a.entry_comment_id = b.entry_comment_id AND a.user_id = b.user_id;
DELETE FROM favourite a USING favourite b WHERE a.id > b.id AND a.post_id = b.post_id AND a.user_id = b.user_id;
DELETE FROM favourite a USING favourite b WHERE a.id > b.id AND a.post_comment_id = b.post_comment_id AND a.user_id = b.user_id;
```

On gehirneimer I had ~13000 duplicates

**Comment by e-five256** [comment]
Did some digging and it seems like this [was fixed upstream](https://codeberg.org/Kbin/kbin-core/src/commit/26e54213cc6bbcf124157c6bced3785b344984b5/src/Entity/Favourite.php#L28-L31) and we'll likely want to do the same

I think this should also give an idea ahead of running the above on how many dupes there are based on how we do vote counts / how asdfzdfj made a sql to track down dupes in a long past issue

```sql
SELECT type, duplicates FROM (
    SELECT 'entry' AS type, count(*) AS duplicates FROM favourite
    GROUP BY entry_id, user_id
    HAVING COUNT(entry_id) > 1
    UNION
    SELECT 'entry_comment'  AS type, count(*) AS duplicates FROM favourite
    GROUP BY entry_comment_id, user_id
    HAVING COUNT(entry_comment_id) > 1
    UNION
    SELECT 'post' AS type, count(*) AS duplicates FROM favourite
    GROUP BY post_id, user_id
    HAVING COUNT(post_id) > 1
    UNION
    SELECT 'post_comment' AS type, count(*) AS duplicates FROM favourite
    GROUP BY post_comment_id, user_id
    HAVING COUNT(post_comment_id) > 1
) d;
```

**Comment by melroy89** [comment]
Related pr (ignore the PR name): https://codeberg.org/Kbin/kbin-core/commit/26e54213cc6bbcf124157c6bced3785b344984b5
