### ISSUE TITLE
Verification mails not being sent

### ISSUE THREAD

**Issue by TheVillageGuy** [MbinOrg/mbin#640]
When registering a new user no verification mail is sent. No errors are reported

bin/console mailer:test works

Verified by originallucifer & @BentiGorlich

**Comment by melroy89** [comment]
A user ([Elley Smith](https://mastodon.melroy.org/@jeze@kzoo.to)) also complaint about this. I thought it was my server.

**Comment by melroy89** [comment]
Fixed by: https://github.com/MbinOrg/mbin/pull/645
