### ISSUE TITLE
Mobile sidebar footer in light mode not readable

### ISSUE THREAD

**Issue by e-five256** [MbinOrg/mbin#66]
With the addition of the footer to the sidebar in #63, in the light theme it is gaining the background of the section (`kbin-section-bg`) which is light and the text color (`kbin-footer-link-color`) which is light. This leads to it being unreadable.

~~There is also an issue where, with the sidebar open, the footer in the sidebar and the footer appear, leading to seeing both of them, but I'm not sure if this is intended or not.~~ not a bug

The screenshot shows the sidebar footer in light mode.

![Screenshot from 2023-10-17 22-02-50](https://github.com/MbinOrg/mbin/assets/146029455/9f8f0228-918e-4fb7-a2ee-55281c415161)

**Comment by simonrcodrington** [comment]
I think the idea with the footer in the sidebar was just so you could get to the bottom of the page on mobile in places where you had infinite scroll (where beforehand you could never get to the bottom)

In cases where there's no infinite scroll, we're gonna get a double footer here on mobile (one in the sidebar and then the original footer at the bottom) . Though, if you have the sidebar open, you shouldn't be able to see the original footer (as the sidebar should be full height on mobile)

The coloring for the theme is definitely an issue. I'll schedule it in to have a look. Most likely we'll define some specific colors for it when the footer appears in the mobile sidebar

**Comment by melroy89** [comment]
@simonrcodrington Thanks in advance to picking this up.

**Comment by melroy89** [comment]
@simonrcodrington  It's only in the mobile sidebar footer indeed the "normal footer" doesn't have this issue..

**Comment by e-five256** [comment]
no longer an issue now that the information is in the sidebar with the same styling as the other sidebar components
