### ISSUE TITLE
Article thumbnails no longer present

### ISSUE THREAD

**Issue by e-five256** [MbinOrg/mbin#692]
**Describe the bug**

Incoming article thumbnails are no longer present

Compare
https://kbin.run/d/theguardian.com
https://fedia.io/d/theguardian.com

https://kbin.run/d/bloomberg.com
https://fedia.io/d/bloomberg.com

**On which Mbin instance did you find the bug?**
kbin.run

**Which Mbin version was running on the instance?**
\>1.5.2

**Expected behavior**
Article entries to have thumbnails

**Screenshots**

| kbin.run | fedia.io |
|-|-|
| ![image](https://github.com/MbinOrg/mbin/assets/146029455/04173c8b-b95c-4848-8ea6-3d4c08856837) | ![image](https://github.com/MbinOrg/mbin/assets/146029455/0dfdb998-1d29-4865-a06d-b7efae5e637f) |

**Comment by nobodyatroot** [comment]
[kbin.run](https://kbin.run/) almost always runs the latest main (and sometimes experimental PRs...), but I'm guessing it's related to this https://github.com/MbinOrg/mbin/pull/650, thoughts @asdfzdfj? if you need more info, let me know what to pull out of the logs.

**Comment by asdfzdfj** [comment]
> [kbin.run](https://kbin.run/) almost always runs the latest main (and sometimes experimental PRs...), but I'm guessing this issue is related to #650. thoughts, @asdfzdfj? if you need more info let me know what to pull out of the logs and/or database.

if possible, could you sample some error logs for `EntryEmbedMessage` or `AttachEntryEmbedHandler` and nearby that uses/mentions the affected link that's missing the cover? also, if you have debug log enabled (somehow), try to search for `Embed:fetch: fetch success` in them that mentions the affected url, thanks

I think I got at least one way it failed which should explains the guardian case but does not for bloomberg, so there may be more way things went wrong

**Comment by e-five256** [comment]
That seems to have helped https://kbin.run/d/theguardian.com/newest

But https://kbin.run/d/bloomberg.com/newest and https://kbin.run/d/thehill.com/newest still no dice while they appear to work fine in 1.5.2

**Comment by e-five256** [comment]
I see what you're saying that it might be non-mbin problem. Let me try to consolidate some stats on who `thehill.com` thumbnails work for

❌ - debounced
✔️ - jerry
❌ - melroy
✔️ - benti (both instances)
❌ - thepaperpilot
✔️ - mozz

Well, interesting data I guess

**Comment by e-five256** [comment]
Based on https://news.ycombinator.com/item?id=19093945 it seems other sites also have trouble getting content from bloomberg, perhaps I will close this as not something mbin can do anything about if people think that is accurate

**Comment by e-five256** [comment]
It looks like thumbnails stopped appearing on fedia for `bloomberg` and `thehill` 4 weeks ago for both. There wasn't an mbin release during that timeframe, so perhaps it is unrelated to mbin, but as there isn't enough info, I'm just going to close this for now
