### ISSUE TITLE
No longer able to view Settings

### ISSUE THREAD

**Issue by NonITExpert** [MbinOrg/mbin#711]
**Describe the bug**
Only Theme can be viewed in Settings. No other settings categories are visible.

**On which Mbin instance did you find the bug?**
kbin.melroy.org

**Which Mbin version was running on the instance?**
1.5.2

**To Reproduce**
1. Go to sidebar
2. Click on settings icon
3. See that only Theme is visible and accessible

**Expected behavior**
In the past, when settings was open, the following categories were visible to manage: Theme, General, Threads, Microblog, Post, Usability Pack. Now only Theme is visible.
![Screenshot_20240414_135019_Firefox Nightly](https://github.com/MbinOrg/mbin/assets/138516886/df170c7b-8ac9-450b-8a44-15e7082c062d)

**Screenshots**
See screenshot

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - Device: Note10+
 - OS: 12.1
 - Browser: Firefox Nightly
 - Browser Version: 126.0a1

**Additional context**

**Comment by UmBottesWillen** [comment]
I can't confirm this bug for 1.5.3 on fedia.io. I still have the settings.

**Comment by e-five256** [comment]
I see a wrench on the sidebar options there, is that perhaps KES?

**Comment by NonITExpert** [comment]
> Edit: hmm, yes it is, but I can't repro it (on melroy's site) with KES on desktop (well, with no options enabled, not sure which ones you might have enabled) or on mobile without KES, maybe will have to try with KES on mobile. But it might be worth trying disabling it just to see if that's it?

As soon as I disabled KES in Tampermonkey, all settings options reappeared. 
![Screenshot_20240414_162647_Firefox Nightly](https://github.com/MbinOrg/mbin/assets/138516886/ee071374-7029-4123-b8a6-99e4c233746f)

**Comment by e-five256** [comment]
If you're able to help narrow it down to what setting might be doing it, that could help me debug it and provide the information on what is happening either to the KES repo or see if we can make changes to accommodate it. If not, I can try to go through every option and try to find it. It just might be easier for you if you have like, one option enabled to narrow it down, as just enabling it didn't seem to cause it for me, so I imagine it's a specific setting, and will have to try all of them to find it.

**Comment by NonITExpert** [comment]
I've tried every combination, diabling 1 by 1, and nothing changes. I've also tried leaving KES enabled in Tampermonkey but leaving all features within KES disabled. logged out and back in, cleared browser cache, restarted phone. No change. I will leave KES disabled in Tampermonkey moving forward.

**Comment by e-five256** [comment]
I installed KES and enabled every option but wasn't able to repro this, so any further information you could provide might be helpful here

**Comment by nobodyatroot** [comment]
closing as seems to be KES specific (and may no longer be relevant as this issue has been open for a long time)
