### ISSUE TITLE
SimpleLogin SSO

### ISSUE THREAD

**Issue by codenyte** [MbinOrg/mbin#754]
**Is your feature request related to a problem? Please describe.**
The current SSO options, Google and GitHub aren't very privacy friendly. A private alternative would be great.

**Describe the solution you'd like**
[Sign in with SimpleLogin (SIWSL)](https://simplelogin.io/docs/siwsl/intro/)

**Describe alternatives you've considered**
N/A

**Additional context**
Screenshot of a forum that implements SIWSL:
![](https://github.com/MbinOrg/mbin/assets/39193783/3865aed4-0124-48dd-b3ab-0d84b7de4938)

**Comment by nobodyatroot** [comment]
@codenyte i made a PR for this, wouldn't mind someone else testing it out. i checked it in dev and everything seems to work.

https://github.com/MbinOrg/mbin/pull/762

**Comment by nobodyatroot** [comment]
> Thank you very much for the quick response and implementation, but I'm not quite sure how to test this. The README says:
> 
> > Developer server explained (see "Developers" section down below)
> 
> But I couldn't find a "Developers" section below. Could you give me some quick instructions on how to set this up, so I can test it?

Good catch, it should point to this: https://docs.joinmbin.org/contributing/developement_server

If you're not familiar with running a kbin/Mbin server, we can wait until https://github.com/MbinOrg/mbin/pull/654 is merged (I've been testing on kbin.run), then I can load up https://github.com/MbinOrg/mbin/pull/762

**Comment by nobodyatroot** [comment]
> Thanks for implementing this! There's just one tiny thing I would change: Currently, the SIWSL option just seems to use a generic icon, maybe [this icon](https://simpleicons.org/?q=simplelogin) from [Simple Icons](https://github.com/simple-icons/simple-icons) could be added? It's licensed under CC0.

I made a PR for this: https://github.com/MbinOrg/mbin/pull/781
