### ISSUE TITLE
trying to register gives 500 internal server error

### ISSUE THREAD

**Issue by Die4Ever** [MbinOrg/mbin#768]
**Describe the bug**
Trying to register gives 500 internal server error. I tried Incognito mode too and it didn't help.

**On which Mbin instance did you find the bug?**
https://kbin.run/

**Which Mbin version was running on the instance?**
1.5.3

**To Reproduce**
1. Go to https://kbin.run/register
2. Fill out form and submit
3. See 500 error

**Screenshots**
![image](https://github.com/MbinOrg/mbin/assets/30947252/2b5dd03f-753b-4cc3-8cbc-5b079cd3170b)

![image](https://github.com/MbinOrg/mbin/assets/30947252/ec56201f-9881-4f09-ba4f-03fff1389836)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Browser Version 124.0.6367.119 (Official Build) (64-bit)

**Comment by nobodyatroot** [comment]
Thanks, I've found the error in the log... need to investigate why it's happening.

```
{"message":"Uncaught PHP Exception Error: \"Call to a member function resolve() on null\" at RegisterController.php line 41","context":{"exception":{"class":"Error","message":"Call to a member function resolve() on null","code":0,"file":"/var/www/kbin/src/Controller/Security/RegisterController.php:41"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2024-05-05T23:05:45.941493+00:00","extra":{}}
{"message":"Uncaught PHP Exception Error: \"Call to a member function resolve() on null\" at RegisterController.php line 41","context":{"exception":{"class":"Error","message":"Call to a member function resolve() on null","code":0,"file":"/var/www/kbin/src/Controller/Security/RegisterController.php:41"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2024-05-05T23:06:27.612600+00:00","extra":{}}

**Comment by nobodyatroot** [comment]
Think we found it, @e-five256 is investigating

**Comment by nobodyatroot** [comment]
@Die4Ever kbin.run has been updated, you should be able to register now. kbin.run is my guinea pig for the most recent main + some PRs that need real federated activity for evaluation... so sometimes this happens, oops. thanks, @e-five256 for the quick PR to fix it!

**Comment by Die4Ever** [comment]
thanks for the quick fix!
