### ISSUE TITLE
Save posts/comments

### ISSUE THREAD

**Issue by codenyte** [MbinOrg/mbin#771]
**Is your feature request related to a problem? Please describe.**
Sometimes I find a interesting or helpful post that I want to save for later. Other (including federated) social media platforms have built-in solutions for this. I think this would be a great improvement for Mbin.

**Describe the solution you'd like**
A save feature for threads, comments, microblogs and replies. Similar to Lemmy, Reddit and Mastodon.

**Describe alternatives you've considered**
Using some other solutions to save links of posts/comments. Not a great solution though.

**Comment by BentiGorlich** [comment]
duplicate of #46
