### ISSUE TITLE
can't view uploaded image in thread

### ISSUE THREAD

**Issue by Shitsurei-shimasu** [MbinOrg/mbin#780]
**Describe the bug**
Started a new thread at lemmyshitpost@lemmy.world.
Uploaded image thru mbin but after posting I can't view it thru mbin. I click on the icon and it just reloads the comments. I go into the sub menu and click open original URL but still doesn't load. This is on the mobile web page. It seems this happens sometimes, other times I can click thru and view image. I usually go straight to the instance to post because of this issue. Does not happen when I post at lemmy.world and view thru mbin.

**On which Mbin instance did you find the bug?**
Kbin.run

**Which Mbin version was running on the instance?**
[e.g. 1.4.0]
1.5.3

**To Reproduce**
1. Go to https://kbin.run/m/lemmyshitpost@lemmy.world/t/420733/Congrats-to-all-2024-college-graduates
2. Click on image icon
3. Image won't appear in mobile. Desktop you can click on the thumbnail to view.

**Expected behavior**
Image should load if you click on the title or image icon

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: pixel 7
 - latest android
 - Browser firefox
 - Browser Version 125.3.0
![Screenshot_20240514-163818](https://github.com/MbinOrg/mbin/assets/21995163/d592529f-c38c-44ec-bfd0-83e0fcc744f2)

**Comment by nobodyatroot** [comment]
@Shitsurei-shimasu i'm almost 100% sure, but can you confirm this entry was made with the "add new thread" function?

![image](https://github.com/MbinOrg/mbin/assets/35878315/a27ee6a6-18bb-4d26-88fa-001f718e399e)

**Comment by Shitsurei-shimasu** [comment]
Yes I can. It is the way I post every time. I click on the add attachment
button and upload the image. This is not the first time it has happened.
Kbin has the same problem.

**Comment by nobodyatroot** [comment]
@Shitsurei-shimasu i updated my original post with some ideas, but can you check your settings menu (hamburger menu -> gear icon) to see if you have "show thumbnails" setting enabled? a photo attached to a thread does not behave the same as submitting a photo entry... but i see there's no text body available to input for a photo entry for whatever reason...

**Comment by Shitsurei-shimasu** [comment]
Ok that does work. I had it disabled because on mobile I prefer it to show
the full size when I scroll. I will just do the add new photo option from
now on if that works as well.

**Comment by Shitsurei-shimasu** [comment]
Just to show my preferred layout. I don't have thumbnails active because I think it makes the feed messy. My way shows full size image for those posts, and just the title for text posts
![Screenshot_20240514-182721](https://github.com/MbinOrg/mbin/assets/21995163/8d247ad5-4357-4897-9c56-b43b748521bc)

**Comment by nobodyatroot** [comment]
@Shitsurei-shimasu can you check to see if Mbin 1.7.0 solves this issue? you should now be able to edit a photo thread and add a body, photo creation does not have a body field present... this is on the radar for a future fix.

**Comment by aaronliu0130** [comment]
I am currently unable to make any photo post. After clicking the button, it shows up as a thread post without a body or image.

**Comment by nobodyatroot** [comment]
> I am currently unable to make any photo post. After clicking the button, it shows up as a thread post without a body or image. See https://kbin.melroy.org/m/random/t/396618/my-image-posts-aren-t-having-the-images-show-up-so and related. Worked yesterday

something happened... my MAX_IMAGE_SIZE default is missing from the config now, investigating

**Comment by nobodyatroot** [comment]
> I am currently unable to make any photo post. After clicking the button, it shows up as a thread post without a body or image. See https://kbin.melroy.org/m/random/t/396618/my-image-posts-aren-t-having-the-images-show-up-so and related. Worked yesterday

ok, its fixed now. thanks for catching that!

**Comment by aaronliu0130** [comment]
I'm guessing kbin.melroy.org still has to update?

**Comment by BentiGorlich** [comment]
Yeah, melroy is on vacation :D

**Comment by nobodyatroot** [comment]
so as to not pollute this issue, im going to close it unless @Shitsurei-shimasu has additional comments/observations related to the original issue.
