### ISSUE TITLE
Why was the ability to sort posts on profiles removed compared to kbin?

### ISSUE THREAD

**Issue by Pamasich** [MbinOrg/mbin#790]
kbin allows changing how posts on profiles are sorted, but it seems that functionality is missing in mbin. Why was it removed?
Is there any other way to look for one's best posts, if I ever want to?

**Comment by e-five256** [comment]
I could be reading it wrong, but it looks like rather [that was added in RTR35](https://codeberg.org/Kbin/kbin-core/commit/ba5b6997760e91b0e21d526834f6d54a9fc15df8#diff-8bda4c9c23de06f93487e15d8e3172085a0a8bd2)

**Comment by Pamasich** [comment]
> I could be reading it wrong, but it looks like rather [that was added in RTR35](https://codeberg.org/Kbin/kbin-core/commit/ba5b6997760e91b0e21d526834f6d54a9fc15df8#diff-8bda4c9c23de06f93487e15d8e3172085a0a8bd2)

Oh yeah, thanks for pointing that out. I'll close this then and do a feature request issue instead.
