### ISSUE TITLE
OAUTH2 support for Privacy Portal Provider

### ISSUE THREAD

**Issue by privacyguard** [MbinOrg/mbin#792]
We have implemented OAUTH2 support for the [Privacy Portal](https://privacyportal.org) provider in our [mbin fork](https://github.com/privacyportal/mbin).

Is there any interest in getting this back into the main repo? Privacy Portal is a privacy focused and free OAUTH2 provider. It uses passwordless authentication and has integrated email aliases for privacy. When someone signs in using the Privacy Portal OAUTH2, mbin would receive a Privacy Alias instead of the real user email.

If you would like to test this, it's deployed on our community mbin node:
https://community.privacyportal.org/login

![mbin_screenshot](https://github.com/MbinOrg/mbin/assets/92675882/32fd1f36-bfea-427f-9f78-d65d7760225d)

**Comment by BentiGorlich** [comment]
Integrating additional SSO providers is always appreciated :+1:

**Comment by nobodyatroot** [comment]
Closed by https://github.com/MbinOrg/mbin/pull/818
