### ISSUE TITLE
Add a "watch" button in order to get magazine notifications

### ISSUE THREAD

**Issue by jwr1** [MbinOrg/mbin#815]
**Is your feature request related to a problem? Please describe.**

At the moment, the only way to receive notifications from a magazine is to subscribe to it and enable "New threads (links or articles) in any magazine to which I'm subscribed" in the notification settings. This isn't ideal because you also subscribe to a magazine to have its threads show in your (subscription) feed, which means you'll get a notification for every single thread that's created in your feed. This could easily add up to hundreds of notifications every day. It would be nice, instead, if subscribed magazines and watched (notifications) magazines could be separate things.

**Describe the solution you'd like**

As I mentioned, it'd be nice if you could separately subscribe and/or watch (for notifications) a magazine. This would probably end up being similar to Reddit, where you can "Join" (subscribe) to a subreddit to have it show up on your homepage/feed, but you can also set the notification settings for a subreddit and have you be notified every time there's a new post or comment.

Basically, I want there to be a notification/watch button next to each magazine that notifies you every time there's activity in the magazine.

**Describe alternatives you've considered**

One alternative is instead of subscribing to things I'm interested in, I could block magazines I'm **not** interested in. That way, I could subscribe to magazines I want notifications for (and enable the subscription notifications setting) and use the "All" feed while browsing.

I don't really like this idea, though, because it means I have to go through every single magazine/user that shows up in my feed and block the ones I don't want to see instead of simply subscribing to what I want. Additionally, while the fediverse is generally small at the moment, as more and more magazines are created, it makes this alternative even less viable.

**Additional Context**

This "watch" button could also be added to users and domains (since you can also subscribe and block both of those), but it's not my priority and could be added at a later time (a separate issue) if it adds too much work.

**Comment by BentiGorlich** [comment]
I'd close this in favor of #1063 as it expands the scope of this one. If that is fine with you @jwr1 you can just close this, the issues are already linked :)

**Comment by jwr1** [comment]
:tada: That's even better! I didn't want to cause too much work, so I tried to keep the scope small.
