### ISSUE TITLE
First letter of new tags is sometimes partially cut off (e.g., the letter "j")

### ISSUE THREAD

**Issue by MHLoppy** [MbinOrg/mbin#822]
**Describe the bug**
As per title; when "j" is the first letter while entering a new tag, the bottom and left sides are cut off, making it appear as an "i" instead. It also seems to occur similarly for other letters like "y" and "p", though I haven't carefully tested all letters. However, it can be observed that it's not (obviously, at least) happening with other letters such as "a".

**On which Mbin instance did you find the bug?**
fedia.io ( https://fedia.io/ )

**Which Mbin version was running on the instance?**
1.6.0

**To Reproduce**
1. Submit something new (as far as I know, type of submission doesn't matter?).
2. Begin typing in a new tag starting with the letter "j", but don't add it yet.
3. Part of the letter "j" is obscured.
4. (if the tag is then added, the "processed" tag does not seem to have the problem; similarly, adding a new first letter makes the full letter "j" appear)

**Expected behavior**
The full letter should be visible.

**Screenshots**
![image](https://github.com/MbinOrg/mbin/assets/12670674/d8eb9eb6-41f7-47aa-9091-b35f3c7e602c)
![image](https://github.com/MbinOrg/mbin/assets/12670674/b629f8ee-c00f-40d4-8a88-709eee804e0a)

**Desktop (please complete the following information):**
 - Windows 10 (build 19045.4291)
 - Mozilla Firefox
 - 125.0.3 (64-bit)

~~**Smartphone (please complete the following information):**~~
N/A

**Additional context**
The problem and screenshots are from just over a week ago (!), I was just late to action it here.

**Comment by nobodyatroot** [comment]
I found this is related to the "autocomplete" feature that is making the tags into the nice boxes... https://symfony.com/bundles/ux-autocomplete/current/index.html#using-with-a-texttype-field

Turning off autocomplete makes this problem go away, but I'd like to understand what the CSS is doing to cause this... I think it's the border css.
