### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by chris-y** [MbinOrg/mbin#832]
Is there a public API?

I can see the docs at https://docs.joinmbin.org/api/ but it's very minimal. 

Specifically I want to know if it is possible to get a subscriber count from an API without logging in.

**Comment by nobodyatroot** [comment]
If the Mbin instance you're using has the API configured correctly, you can visit /api/docs, e.g., https://kbin.run/api/docs

**Comment by chris-y** [comment]
Excellent, thanks. Would be nice if this was replicated in the documentation.

**Comment by nobodyatroot** [comment]
https://docs.joinmbin.org/api/ has all the same information as `/api/docs`, but the formatting is different. either way... if you discover that we're missing a feature of the API that you'd like to see, we wouldn't say no to a feature request. :-)

**Comment by BentiGorlich** [comment]
https://docs.joinmbin.org/api/ contains the same information as the other endpoint, just in a different format

**Comment by chris-y** [comment]
Ok, that's the address I looked at originally and it only had oauth flow, I didn't see anything about actually accessing the API. Anyway, sorted now, thanks.
