### ISSUE TITLE
Fedia.io hasn't updated federated content in 6 hours

### ISSUE THREAD

**Issue by downpunxx** [MbinOrg/mbin#845]
**Describe the bug**
fedia.io hasn't updated federated content in 6 hrs

**On which Mbin instance did you find the bug?**
fedia.io
![Screenshot 2024-06-20 025035 - Copy](https://github.com/MbinOrg/mbin/assets/173356204/8b915ca8-c0a5-4923-bfd9-9ddc6fa513f3)

**Which Mbin version was running on the instance?**
[e.g. 1.4.0]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Version [e.g. 123]

**Smartphone (please complete the following information):**
 - Browser Version [e.g. 123]

**Additional context**

**Comment by BentiGorlich** [comment]
That is not an mbin issue, but a fedia one. Please try to contact your admin directly
