### ISSUE TITLE
Internal Error 500 when searching any User

### ISSUE THREAD

**Issue by oscarsmendez** [MbinOrg/mbin#858]
**Describe the bug**
I setup an mbin instance using docker and everything is working fine however, when searching for any user inside or outside the instance I receive the Internal error 500.

Edit: I attempted to search on localhost it doesn't spit out an error but instead the search shows up empty. It also doesn't let me login on localhost but I'm assuming that's intentional? I'm hosting it through a cloudflare tunnel so hopefully that's not the issue

In the mbin php console this seems to be where it goes wrong but I'm not too sure:

mbin-php       | {"message":"Uncaught PHP Exception TypeError: \"App\\Service\\ActivityPub\\ApHttpClient::getInstancePrivateKey(): Return value must be of type string, null returned\" at ApHttpClient.php line 398","context":{"exception":{"class":"TypeError","message":"App\\Service\\ActivityPub\\ApHttpClient::getInstancePrivateKey(): Return value must be of type string, null returned","code":0,"file":"/var/www/mbin/src/Service/ActivityPub/ApHttpClient.php:398"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2024-06-23T01:58:48.073284+00:00","extra":{}}

**On which Mbin instance did you find the bug?**
falsepanda.social

**Which Mbin version was running on the instance?**
1.6.0

**To Reproduce**
1. Follow the steps in the docker instructions 
2. Go to the search icon and enter any user from the fediverse

**Expected behavior**
Searching to be possible

**Screenshots**
![Screenshot 2024-06-22 at 10 06 56 PM](https://github.com/MbinOrg/mbin/assets/82800214/6f864583-7737-4493-93df-fc2480194eef)

**Desktop (please complete the following information):**
 - OS: MacOS/Docker
 - Browser: Arc
 - Browser Version: latest

**Comment by e-five256** [comment]
Try this to see if it helps https://docs.joinmbin.org/admin/FAQ#running-php-binconsole-mbinapkeysupdate-does-not-appear-to-set-keys

**Comment by melroy89** [comment]
Try to clear Redis.

**Comment by oscarsmendez** [comment]
I tried clearing redis as well as looking through rabbitmq and it did remind me I set up the docker compose command using just async, "command: 'sh -c "php bin/console messenger:consume async --time-limit=3600"'" as using the default command immediately crashed messenger, 
![Screenshot 2024-07-03 at 3 40 44 AM](https://github.com/MbinOrg/mbin/assets/82800214/2c7a73de-4b1d-4b1e-b1d5-d5a46277bec8)
I can try running it on bare-metal next week to see if I get the same reaction

**Comment by BentiGorlich** [comment]
You gotta give us some log entries for us to help you :)
Just have a look at the logs while trying to do what you are doing and you should see the error message there

**Comment by BentiGorlich** [comment]
And the default command is not optional. You have to use that, otherwise federation will not or only partially work

**Comment by BentiGorlich** [comment]
And the internal server error is not caused by your messengers. They do not interact that way with each other, so the queues are not the problem here. I guess you just didn't run the key generation: `docker compose exec php php bin/console mbin:ap:keys:update`

**Comment by oscarsmendez** [comment]
It was definitely the keys, I was able to end up using the default command too, I have a php problem now with opening federated magazines but it seems unrelated so I'll open a different issue for that, thanks for ya'll's help!
