### ISSUE TITLE
After signing in with SSO, redirect to user profile

### ISSUE THREAD

**Issue by TheVillageGuy** [MbinOrg/mbin#890]
When signing in using an SSO, e.g. google, discord, if the username already exists it is made by adding a random number. This can only be changed until, for instance, an upvote is made.

Google based usernames are always made based on google name + random number

Instead of bringing the user to https://my.mbin it should bring them to https://my.mbin/settings/profile so they can change their username (maybe clarify that this can only be done until they interact)

**Comment by BentiGorlich** [comment]
> the username is made using a random number

Just to clarify, this only happens when a user with the username already exists

**Comment by TheVillageGuy** [comment]
> Just to clarify, this only happens when a user with the username already exists

Good point, I have added this to my initial comment.
