### ISSUE TITLE
error 500 when saving on the admin settings

### ISSUE THREAD

**Issue by CocoPoops** [MbinOrg/mbin#996]
**Describe the bug**
500 Internal Server Error when saving on an instances admin panel settings which causes settings to not be saved
https://mbin.cocopoops.com/admin/settings

**On which Mbin instance did you find the bug?**
mbin.cocopoops.com

**Which Mbin version was running on the instance?**
1.7.0

**To Reproduce**
1. Login to Admin User 
2. Go to the Admin Panel of the instance
3. Click Settings
4. Click Save at the bottom of the form

**Comment by BentiGorlich** [comment]
Can confirm this. Super annoying, no idea whats causing it (didn't look at the logs yet)

**Comment by BentiGorlich** [comment]
```json
{
    "message": "Uncaught PHP Exception TypeError: \"App\\Entity\\Settings::__construct(): Argument #2 ($value) must be of type array|string, int given, called in /var/www/kbin/src/Service/SettingsManager.php on line 115\" at Settings.php line 29",
    "context": {
        "exception": {
            "class": "TypeError",
            "message": "App\\Entity\\Settings::__construct(): Argument #2 ($value) must be of type array|string, int given, called in /var/www/kbin/src/Service/SettingsManager.php on line 115",
            "code": 0,
            "file": "/var/www/kbin/src/Entity/Settings.php:29"
        }
    },
    "level": 500,
    "level_name": "CRITICAL",
    "channel": "request",
    "datetime": "2024-08-05T08:17:02.409964+00:00",
    "extra": {}
}
```
